/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as LoginRouteImport } from './routes/login'
import { Route as AuthRouteImport } from './routes/_auth'
import { Route as CatchallRouteImport } from './routes/$catchall'
import { Route as AuthIndexRouteImport } from './routes/_auth/index'
import { Route as AuthWafRouteImport } from './routes/_auth/waf'
import { Route as AuthSslRouteImport } from './routes/_auth/ssl'
import { Route as AuthSitesRouteImport } from './routes/_auth/sites'
import { Route as AuthPerformanceRouteImport } from './routes/_auth/performance'
import { Route as AuthOperatorsRouteImport } from './routes/_auth/operators'
import { Route as AuthNodesRouteImport } from './routes/_auth/nodes'
import { Route as AuthLogsRouteImport } from './routes/_auth/logs'
import { Route as AuthLoadBalancingRouteImport } from './routes/_auth/load-balancing'
import { Route as AuthIpFirewallRouteImport } from './routes/_auth/ip-firewall'
import { Route as AuthDashboardRouteImport } from './routes/_auth/dashboard'
import { Route as AuthBackupRouteImport } from './routes/_auth/backup'
import { Route as AuthAlertingRouteImport } from './routes/_auth/alerting'
import { Route as AuthAccountRouteImport } from './routes/_auth/account'
import { Route as AuthAccessPoliciesRouteImport } from './routes/_auth/access-policies'

const LoginRoute = LoginRouteImport.update({
  id: '/login',
  path: '/login',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/_auth',
  getParentRoute: () => rootRouteImport,
} as any)
const CatchallRoute = CatchallRouteImport.update({
  id: '/$catchall',
  path: '/$catchall',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthIndexRoute = AuthIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => AuthRoute,
} as any)
const AuthWafRoute = AuthWafRouteImport.update({
  id: '/waf',
  path: '/waf',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSslRoute = AuthSslRouteImport.update({
  id: '/ssl',
  path: '/ssl',
  getParentRoute: () => AuthRoute,
} as any)
const AuthSitesRoute = AuthSitesRouteImport.update({
  id: '/sites',
  path: '/sites',
  getParentRoute: () => AuthRoute,
} as any)
const AuthPerformanceRoute = AuthPerformanceRouteImport.update({
  id: '/performance',
  path: '/performance',
  getParentRoute: () => AuthRoute,
} as any)
const AuthOperatorsRoute = AuthOperatorsRouteImport.update({
  id: '/operators',
  path: '/operators',
  getParentRoute: () => AuthRoute,
} as any)
const AuthNodesRoute = AuthNodesRouteImport.update({
  id: '/nodes',
  path: '/nodes',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLogsRoute = AuthLogsRouteImport.update({
  id: '/logs',
  path: '/logs',
  getParentRoute: () => AuthRoute,
} as any)
const AuthLoadBalancingRoute = AuthLoadBalancingRouteImport.update({
  id: '/load-balancing',
  path: '/load-balancing',
  getParentRoute: () => AuthRoute,
} as any)
const AuthIpFirewallRoute = AuthIpFirewallRouteImport.update({
  id: '/ip-firewall',
  path: '/ip-firewall',
  getParentRoute: () => AuthRoute,
} as any)
const AuthDashboardRoute = AuthDashboardRouteImport.update({
  id: '/dashboard',
  path: '/dashboard',
  getParentRoute: () => AuthRoute,
} as any)
const AuthBackupRoute = AuthBackupRouteImport.update({
  id: '/backup',
  path: '/backup',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAlertingRoute = AuthAlertingRouteImport.update({
  id: '/alerting',
  path: '/alerting',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccountRoute = AuthAccountRouteImport.update({
  id: '/account',
  path: '/account',
  getParentRoute: () => AuthRoute,
} as any)
const AuthAccessPoliciesRoute = AuthAccessPoliciesRouteImport.update({
  id: '/access-policies',
  path: '/access-policies',
  getParentRoute: () => AuthRoute,
} as any)

export interface FileRoutesByFullPath {
  '/$catchall': typeof CatchallRoute
  '/': typeof AuthIndexRoute
  '/login': typeof LoginRoute
  '/access-policies': typeof AuthAccessPoliciesRoute
  '/account': typeof AuthAccountRoute
  '/alerting': typeof AuthAlertingRoute
  '/backup': typeof AuthBackupRoute
  '/dashboard': typeof AuthDashboardRoute
  '/ip-firewall': typeof AuthIpFirewallRoute
  '/load-balancing': typeof AuthLoadBalancingRoute
  '/logs': typeof AuthLogsRoute
  '/nodes': typeof AuthNodesRoute
  '/operators': typeof AuthOperatorsRoute
  '/performance': typeof AuthPerformanceRoute
  '/sites': typeof AuthSitesRoute
  '/ssl': typeof AuthSslRoute
  '/waf': typeof AuthWafRoute
}
export interface FileRoutesByTo {
  '/$catchall': typeof CatchallRoute
  '/login': typeof LoginRoute
  '/access-policies': typeof AuthAccessPoliciesRoute
  '/account': typeof AuthAccountRoute
  '/alerting': typeof AuthAlertingRoute
  '/backup': typeof AuthBackupRoute
  '/dashboard': typeof AuthDashboardRoute
  '/ip-firewall': typeof AuthIpFirewallRoute
  '/load-balancing': typeof AuthLoadBalancingRoute
  '/logs': typeof AuthLogsRoute
  '/nodes': typeof AuthNodesRoute
  '/operators': typeof AuthOperatorsRoute
  '/performance': typeof AuthPerformanceRoute
  '/sites': typeof AuthSitesRoute
  '/ssl': typeof AuthSslRoute
  '/waf': typeof AuthWafRoute
  '/': typeof AuthIndexRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/$catchall': typeof CatchallRoute
  '/_auth': typeof AuthRouteWithChildren
  '/login': typeof LoginRoute
  '/_auth/access-policies': typeof AuthAccessPoliciesRoute
  '/_auth/account': typeof AuthAccountRoute
  '/_auth/alerting': typeof AuthAlertingRoute
  '/_auth/backup': typeof AuthBackupRoute
  '/_auth/dashboard': typeof AuthDashboardRoute
  '/_auth/ip-firewall': typeof AuthIpFirewallRoute
  '/_auth/load-balancing': typeof AuthLoadBalancingRoute
  '/_auth/logs': typeof AuthLogsRoute
  '/_auth/nodes': typeof AuthNodesRoute
  '/_auth/operators': typeof AuthOperatorsRoute
  '/_auth/performance': typeof AuthPerformanceRoute
  '/_auth/sites': typeof AuthSitesRoute
  '/_auth/ssl': typeof AuthSslRoute
  '/_auth/waf': typeof AuthWafRoute
  '/_auth/': typeof AuthIndexRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/$catchall'
    | '/'
    | '/login'
    | '/access-policies'
    | '/account'
    | '/alerting'
    | '/backup'
    | '/dashboard'
    | '/ip-firewall'
    | '/load-balancing'
    | '/logs'
    | '/nodes'
    | '/operators'
    | '/performance'
    | '/sites'
    | '/ssl'
    | '/waf'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/$catchall'
    | '/login'
    | '/access-policies'
    | '/account'
    | '/alerting'
    | '/backup'
    | '/dashboard'
    | '/ip-firewall'
    | '/load-balancing'
    | '/logs'
    | '/nodes'
    | '/operators'
    | '/performance'
    | '/sites'
    | '/ssl'
    | '/waf'
    | '/'
  id:
    | '__root__'
    | '/$catchall'
    | '/_auth'
    | '/login'
    | '/_auth/access-policies'
    | '/_auth/account'
    | '/_auth/alerting'
    | '/_auth/backup'
    | '/_auth/dashboard'
    | '/_auth/ip-firewall'
    | '/_auth/load-balancing'
    | '/_auth/logs'
    | '/_auth/nodes'
    | '/_auth/operators'
    | '/_auth/performance'
    | '/_auth/sites'
    | '/_auth/ssl'
    | '/_auth/waf'
    | '/_auth/'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  CatchallRoute: typeof CatchallRoute
  AuthRoute: typeof AuthRouteWithChildren
  LoginRoute: typeof LoginRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/login': {
      id: '/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof LoginRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: '/'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/$catchall': {
      id: '/$catchall'
      path: '/$catchall'
      fullPath: '/$catchall'
      preLoaderRoute: typeof CatchallRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/_auth/': {
      id: '/_auth/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof AuthIndexRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/waf': {
      id: '/_auth/waf'
      path: '/waf'
      fullPath: '/waf'
      preLoaderRoute: typeof AuthWafRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/ssl': {
      id: '/_auth/ssl'
      path: '/ssl'
      fullPath: '/ssl'
      preLoaderRoute: typeof AuthSslRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/sites': {
      id: '/_auth/sites'
      path: '/sites'
      fullPath: '/sites'
      preLoaderRoute: typeof AuthSitesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/performance': {
      id: '/_auth/performance'
      path: '/performance'
      fullPath: '/performance'
      preLoaderRoute: typeof AuthPerformanceRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/operators': {
      id: '/_auth/operators'
      path: '/operators'
      fullPath: '/operators'
      preLoaderRoute: typeof AuthOperatorsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/nodes': {
      id: '/_auth/nodes'
      path: '/nodes'
      fullPath: '/nodes'
      preLoaderRoute: typeof AuthNodesRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/logs': {
      id: '/_auth/logs'
      path: '/logs'
      fullPath: '/logs'
      preLoaderRoute: typeof AuthLogsRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/load-balancing': {
      id: '/_auth/load-balancing'
      path: '/load-balancing'
      fullPath: '/load-balancing'
      preLoaderRoute: typeof AuthLoadBalancingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/ip-firewall': {
      id: '/_auth/ip-firewall'
      path: '/ip-firewall'
      fullPath: '/ip-firewall'
      preLoaderRoute: typeof AuthIpFirewallRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/dashboard': {
      id: '/_auth/dashboard'
      path: '/dashboard'
      fullPath: '/dashboard'
      preLoaderRoute: typeof AuthDashboardRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/backup': {
      id: '/_auth/backup'
      path: '/backup'
      fullPath: '/backup'
      preLoaderRoute: typeof AuthBackupRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/alerting': {
      id: '/_auth/alerting'
      path: '/alerting'
      fullPath: '/alerting'
      preLoaderRoute: typeof AuthAlertingRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/account': {
      id: '/_auth/account'
      path: '/account'
      fullPath: '/account'
      preLoaderRoute: typeof AuthAccountRouteImport
      parentRoute: typeof AuthRoute
    }
    '/_auth/access-policies': {
      id: '/_auth/access-policies'
      path: '/access-policies'
      fullPath: '/access-policies'
      preLoaderRoute: typeof AuthAccessPoliciesRouteImport
      parentRoute: typeof AuthRoute
    }
  }
}

interface AuthRouteChildren {
  AuthAccessPoliciesRoute: typeof AuthAccessPoliciesRoute
  AuthAccountRoute: typeof AuthAccountRoute
  AuthAlertingRoute: typeof AuthAlertingRoute
  AuthBackupRoute: typeof AuthBackupRoute
  AuthDashboardRoute: typeof AuthDashboardRoute
  AuthIpFirewallRoute: typeof AuthIpFirewallRoute
  AuthLoadBalancingRoute: typeof AuthLoadBalancingRoute
  AuthLogsRoute: typeof AuthLogsRoute
  AuthNodesRoute: typeof AuthNodesRoute
  AuthOperatorsRoute: typeof AuthOperatorsRoute
  AuthPerformanceRoute: typeof AuthPerformanceRoute
  AuthSitesRoute: typeof AuthSitesRoute
  AuthSslRoute: typeof AuthSslRoute
  AuthWafRoute: typeof AuthWafRoute
  AuthIndexRoute: typeof AuthIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthAccessPoliciesRoute: AuthAccessPoliciesRoute,
  AuthAccountRoute: AuthAccountRoute,
  AuthAlertingRoute: AuthAlertingRoute,
  AuthBackupRoute: AuthBackupRoute,
  AuthDashboardRoute: AuthDashboardRoute,
  AuthIpFirewallRoute: AuthIpFirewallRoute,
  AuthLoadBalancingRoute: AuthLoadBalancingRoute,
  AuthLogsRoute: AuthLogsRoute,
  AuthNodesRoute: AuthNodesRoute,
  AuthOperatorsRoute: AuthOperatorsRoute,
  AuthPerformanceRoute: AuthPerformanceRoute,
  AuthSitesRoute: AuthSitesRoute,
  AuthSslRoute: AuthSslRoute,
  AuthWafRoute: AuthWafRoute,
  AuthIndexRoute: AuthIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

const rootRouteChildren: RootRouteChildren = {
  CatchallRoute: CatchallRoute,
  AuthRoute: AuthRouteWithChildren,
  LoginRoute: LoginRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()
